apiVersion: v1
items:
- apiVersion: v1
  kind: Pod
  metadata:
    annotations:
      kubectl.kubernetes.io/restartedAt: "2026-05-12T19:34:01+08:00"
    creationTimestamp: "2026-05-12T11:34:01Z"
    generateName: rl-scheduler-867c9b9c79-
    generation: 1
    labels:
      app: rl-scheduler
      app.kubernetes.io/instance: slurm-platform
      app.kubernetes.io/name: slurm-platform
      pod-template-hash: 867c9b9c79
    name: rl-scheduler-867c9b9c79-6djjz
    namespace: slurm
    ownerReferences:
    - apiVersion: apps/v1
      blockOwnerDeletion: true
      controller: true
      kind: ReplicaSet
      name: rl-scheduler-867c9b9c79
      uid: 68676937-95ad-4e39-87ba-f6ea52649fec
    resourceVersion: "2211456"
    uid: 5b9db5c9-1ee5-40af-ae74-88dde24696c4
  spec:
    containers:
    - env:
      - name: SHADOW_MODE
        value: "true"
      - name: SNAPSHOT_TTL_S
        value: "30"
      - name: VALUE_ABSTAIN
        value: "-100"
      - name: ENTROPY_ABSTAIN
        value: "10"
      - name: PRIORITY_BOOST
        value: "1000"
      image: slurm-rl-scheduler:m11
      imagePullPolicy: IfNotPresent
      livenessProbe:
        failureThreshold: 3
        httpGet:
          path: /healthz
          port: http
          scheme: HTTP
        periodSeconds: 30
        successThreshold: 1
        timeoutSeconds: 1
      name: serve
      ports:
      - containerPort: 8002
        name: http
        protocol: TCP
      readinessProbe:
        failureThreshold: 6
        httpGet:
          path: /healthz
          port: http
          scheme: HTTP
        periodSeconds: 5
        successThreshold: 1
        timeoutSeconds: 1
      resources:
        limits:
          cpu: "2"
          memory: 2Gi
        requests:
          cpu: 250m
          memory: 512Mi
      terminationMessagePath: /dev/termination-log
      terminationMessagePolicy: File
      volumeMounts:
      - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
        name: kube-api-access-rj698
        readOnly: true
    dnsPolicy: ClusterFirst
    enableServiceLinks: true
    nodeName: acane
    preemptionPolicy: PreemptLowerPriority
    priority: 0
    restartPolicy: Always
    schedulerName: default-scheduler
    securityContext: {}
    serviceAccount: default
    serviceAccountName: default
    terminationGracePeriodSeconds: 30
    tolerations:
    - effect: NoExecute
      key: node.kubernetes.io/not-ready
      operator: Exists
      tolerationSeconds: 300
    - effect: NoExecute
      key: node.kubernetes.io/unreachable
      operator: Exists
      tolerationSeconds: 300
    volumes:
    - name: kube-api-access-rj698
      projected:
        defaultMode: 420
        sources:
        - serviceAccountToken:
            expirationSeconds: 3607
            path: token
        - configMap:
            items:
            - key: ca.crt
              path: ca.crt
            name: kube-root-ca.crt
        - downwardAPI:
            items:
            - fieldRef:
                apiVersion: v1
                fieldPath: metadata.namespace
              path: namespace
  status:
    conditions:
    - lastProbeTime: null
      lastTransitionTime: "2026-05-12T11:34:02Z"
      observedGeneration: 1
      status: "True"
      type: PodReadyToStartContainers
    - lastProbeTime: null
      lastTransitionTime: "2026-05-12T11:34:01Z"
      observedGeneration: 1
      status: "True"
      type: Initialized
    - lastProbeTime: null
      lastTransitionTime: "2026-05-12T11:34:07Z"
      observedGeneration: 1
      status: "True"
      type: Ready
    - lastProbeTime: null
      lastTransitionTime: "2026-05-12T11:34:07Z"
      observedGeneration: 1
      status: "True"
      type: ContainersReady
    - lastProbeTime: null
      lastTransitionTime: "2026-05-12T11:34:01Z"
      observedGeneration: 1
      status: "True"
      type: PodScheduled
    containerStatuses:
    - allocatedResources:
        cpu: 250m
        memory: 512Mi
      containerID: containerd://112da47d0e4fe0a6786616d49144f7e6da260b295b972432ca50addf06064de5
      image: docker.io/library/slurm-rl-scheduler:m11
      imageID: sha256:0820eab632a58561a0e6094d8a6890ec6472d87448af33b60a3a4491433ff2bf
      lastState: {}
      name: serve
      ready: true
      resources:
        limits:
          cpu: "2"
          memory: 2Gi
        requests:
          cpu: 250m
          memory: 512Mi
      restartCount: 0
      started: true
      state:
        running:
          startedAt: "2026-05-12T11:34:02Z"
      user:
        linux:
          gid: 0
          supplementalGroups:
          - 0
          uid: 0
      volumeMounts:
      - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
        name: kube-api-access-rj698
        readOnly: true
        recursiveReadOnly: Disabled
    hostIP: 192.168.0.111
    hostIPs:
    - ip: 192.168.0.111
    observedGeneration: 1
    phase: Running
    podIP: 10.42.0.176
    podIPs:
    - ip: 10.42.0.176
    qosClass: Burstable
    startTime: "2026-05-12T11:34:01Z"
kind: List
metadata:
  resourceVersion: ""
