apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: slurm-shared-nfs
provisioner: k8s-sigs.io/slurm-nfs-subdir-external-provisioner
reclaimPolicy: Retain
volumeBindingMode: Immediate
allowVolumeExpansion: true
parameters:
  archiveOnDelete: "false"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: slurm-shared-rwx
  namespace: slurm
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 20Gi
  storageClassName: slurm-shared-nfs
